name: Python package

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Install poetry"
        run: |
          pip install poetry
      - name: "Install requirements"
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: Install pytest-cov
        run: |
          pip install pytest-cov
      - name: Test & publish code coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-coverage-tool
          chmod +x ./cc-test-coverage-tool
      - name: Sending Reporter
        env:
          CC_TEST_REPORTER_ID: 8b017fa9332da64c9b3cb4fd9fabd16d64f8a5e8e35f6b367ff1db2aa44f2fc5
        run: |
          ./cc-test-coverage-tool after-build -r "$CC_TEST_REPORTER_ID"
