name: Python package

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Install poetry"
        run: |
          pip install poetry
      - name: "Install requirements"
        run: |
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: Instal pytest-cov
        run: |
          pip install pytest-cov
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test
        run: |
          make test-coverage
      - name: Sending Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN"
